site_name: WebDSL
repo_url: https://github.com/giannisgkountras/web-dsl
repo_name: giannisgkountras/web-dsl
docs_dir: mkdocs-src
site_dir: docs
theme:
    name: material
    logo: assets/images/logo_ball.png
    favicon: assets/images/logo_ball.png
    palette:
        scheme: slate
    custom_dir: overrides
    features:
        - navigation.instant
        - header.repo
        - header.repo.meta
extra_css:
    - stylesheets/extra.css
nav:
    - Home: index.md
    - Usage:
          - Webpage: webpage.md
          - Connections: connections.md
          - Data Sources: datasources.md
          - Entities: entities.md
          - Components: components.md
          - Conditions: conditions.md
          - Loops: loops.md
          - Screens: screens.md
    - Imports: import.md
    - Validation: validation.md
    - Generation: generation.md
    - OpenAPI Transformation: openapi.md
    - GoalDSL Transformation: goaldsl.md
    - Examples: examples.md
